<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/06/11 14:17:10
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'sit_admin',
    ),
  ),
  'general' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'sit_general',
    ),
  ),
);
