<?php


/**
 * This class defines the structure of the 'bit_bitacora' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 31 11:39:53 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class BitBitacoraTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.BitBitacoraTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('bit_bitacora');
		$this->setPhpName('BitBitacora');
		$this->setClassname('BitBitacora');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('bit_bitacora_id_bitacora_seq');
		// columns
		$this->addPrimaryKey('ID_BITACORA', 'IdBitacora', 'INTEGER', true, null, null);
		$this->addColumn('FECHA', 'Fecha', 'DATE', false, null, null);
		$this->addColumn('HORA', 'Hora', 'TIME', false, null, null);
		$this->addColumn('DESCRIPCION', 'Descripcion', 'VARCHAR', false, 500, null);
		$this->addForeignKey('ID_SUBCATEGORIA', 'IdSubcategoria', 'INTEGER', 'bit_subcategorias', 'ID_SUBCATEGORIA', false, null, null);
		$this->addForeignKey('ID_USUARIO', 'IdUsuario', 'INTEGER', 'sf_guard_user_profile', 'USER_ID', false, null, null);
		$this->addForeignKey('ID_UNIDAD', 'IdUnidad', 'INTEGER', 'sit_unidades', 'ID_UNIDAD', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('BitSubcategorias', 'BitSubcategorias', RelationMap::MANY_TO_ONE, array('id_subcategoria' => 'id_subcategoria', ), null, null);
    $this->addRelation('SfGuardUserProfile', 'SfGuardUserProfile', RelationMap::MANY_TO_ONE, array('id_usuario' => 'user_id', ), null, null);
    $this->addRelation('SitUnidades', 'SitUnidades', RelationMap::MANY_TO_ONE, array('id_unidad' => 'id_unidad', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // BitBitacoraTableMap
