<?php


/**
 * This class defines the structure of the 'ct_constancias' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep 14 15:26:10 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CtConstanciasTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CtConstanciasTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('ct_constancias');
		$this->setPhpName('CtConstancias');
		$this->setClassname('CtConstancias');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('ct_constancias_id_constancia_seq');
		// columns
		$this->addPrimaryKey('ID_CONSTANCIA', 'IdConstancia', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_SOLICITANTE', 'IdSolicitante', 'INTEGER', 'sf_guard_user_profile', 'USER_ID', true, null, null);
		$this->addColumn('FECHA_SOLICITUD', 'FechaSolicitud', 'DATE', true, null, null);
		$this->addColumn('TIPO_CONSTANCIA', 'TipoConstancia', 'VARCHAR', true, 3, null);
		$this->addColumn('BONO_ALIMENTACION', 'BonoAlimentacion', 'BOOLEAN', true, null, null);
		$this->addColumn('MOTIVO', 'Motivo', 'VARCHAR', true, 500, null);
		$this->addColumn('DIRIGIDO_A', 'DirigidoA', 'VARCHAR', true, 100, null);
		$this->addColumn('ESTATUS', 'Estatus', 'VARCHAR', true, 1, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SfGuardUserProfile', 'SfGuardUserProfile', RelationMap::MANY_TO_ONE, array('id_solicitante' => 'user_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CtConstanciasTableMap
