<?php


/**
 * This class defines the structure of the 'sit_categorias_unidades' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 31 11:39:56 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SitCategoriasUnidadesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SitCategoriasUnidadesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sit_categorias_unidades');
		$this->setPhpName('SitCategoriasUnidades');
		$this->setClassname('SitCategoriasUnidades');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('ID_CATEGORIA', 'IdCategoria', 'INTEGER' , 'sit_categorias', 'ID_CATEGORIA', true, null, null);
		$this->addForeignKey('ID_UNIDAD', 'IdUnidad', 'INTEGER', 'sit_unidades', 'ID_UNIDAD', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SitCategorias', 'SitCategorias', RelationMap::MANY_TO_ONE, array('id_categoria' => 'id_categoria', ), null, null);
    $this->addRelation('SitUnidades', 'SitUnidades', RelationMap::MANY_TO_ONE, array('id_unidad' => 'id_unidad', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SitCategoriasUnidadesTableMap
