<?php


/**
 * This class defines the structure of the 'tra_solicitudes' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec 27 12:53:46 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TraSolicitudesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TraSolicitudesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tra_solicitudes');
		$this->setPhpName('TraSolicitudes');
		$this->setClassname('TraSolicitudes');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('tra_solicitudes_id_solicitud_seq');
		// columns
		$this->addPrimaryKey('ID_SOLICITUD', 'IdSolicitud', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_SOLICITANTE', 'IdSolicitante', 'INTEGER', 'sf_guard_user_profile', 'USER_ID', true, null, null);
		$this->addColumn('ASISTENTES', 'Asistentes', 'VARCHAR', false, 100, null);
		$this->addColumn('FECHA_SOLICITUD', 'FechaSolicitud', 'DATE', false, null, null);
		$this->addColumn('FECHA_SALIDA', 'FechaSalida', 'DATE', false, null, null);
		$this->addColumn('HORA_SALIDA', 'HoraSalida', 'TIME', false, null, null);
		$this->addColumn('DIRECCION_TRASLADO', 'DireccionTraslado', 'VARCHAR', true, 500, null);
		$this->addColumn('DESCRIPCION_EQUIPOS', 'DescripcionEquipos', 'VARCHAR', false, 500, null);
		$this->addColumn('DATOS_INTERES_RAZON', 'DatosInteresRazon', 'VARCHAR', false, 500, null);
		$this->addColumn('TIPO_TRANSPORTE', 'TipoTransporte', 'VARCHAR', true, 1, null);
		$this->addColumn('TIPO_SOLICITUD', 'TipoSolicitud', 'VARCHAR', true, 1, null);
		$this->addColumn('ESTATUS', 'Estatus', 'VARCHAR', true, 2, '0');
		$this->addColumn('JUSTIFICACION_RECHAZO', 'JustificacionRechazo', 'VARCHAR', false, 500, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SfGuardUserProfile', 'SfGuardUserProfile', RelationMap::MANY_TO_ONE, array('id_solicitante' => 'user_id', ), null, null);
    $this->addRelation('TraAsignaciones', 'TraAsignaciones', RelationMap::ONE_TO_ONE, array('id_solicitud' => 'id_solicitud', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TraSolicitudesTableMap
