<?php


/**
 * This class defines the structure of the 'tsur_direcciones' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec 27 12:53:47 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TsurDireccionesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TsurDireccionesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tsur_direcciones');
		$this->setPhpName('TsurDirecciones');
		$this->setClassname('TsurDirecciones');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('tsur_direcciones_id_direccion_seq');
		// columns
		$this->addPrimaryKey('ID_DIRECCION', 'IdDireccion', 'INTEGER', true, null, null);
		$this->addColumn('DESCRIPCION', 'Descripcion', 'VARCHAR', true, 100, null);
		$this->addForeignKey('ID_VCEPRESIDENCIA', 'IdVcepresidencia', 'INTEGER', 'tsur_vicepresidencias', 'ID_VCEPRESIDENCIA', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('TsurVicepresidencias', 'TsurVicepresidencias', RelationMap::MANY_TO_ONE, array('id_vcepresidencia' => 'id_vcepresidencia', ), null, null);
    $this->addRelation('TsurUnidades', 'TsurUnidades', RelationMap::ONE_TO_MANY, array('id_direccion' => 'id_direccion', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TsurDireccionesTableMap
