<?php

/**
 * Base class that represents a row from the 'sit_unidades' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 24 11:49:54 2012
 *
 * @package    lib.model.om
 */
abstract class BaseSitUnidades extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SitUnidadesPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_unidad field.
	 * @var        int
	 */
	protected $id_unidad;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the correo field.
	 * @var        string
	 */
	protected $correo;

	/**
	 * @var        array BitCategoriasUnidades[] Collection to store aggregation of BitCategoriasUnidades objects.
	 */
	protected $collBitCategoriasUnidadess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBitCategoriasUnidadess.
	 */
	private $lastBitCategoriasUnidadesCriteria = null;

	/**
	 * @var        array SitCategoriasUnidades[] Collection to store aggregation of SitCategoriasUnidades objects.
	 */
	protected $collSitCategoriasUnidadess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSitCategoriasUnidadess.
	 */
	private $lastSitCategoriasUnidadesCriteria = null;

	/**
	 * @var        array SitTickets[] Collection to store aggregation of SitTickets objects.
	 */
	protected $collSitTicketss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSitTicketss.
	 */
	private $lastSitTicketsCriteria = null;

	/**
	 * @var        array SitUsuariosUnidades[] Collection to store aggregation of SitUsuariosUnidades objects.
	 */
	protected $collSitUsuariosUnidadess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSitUsuariosUnidadess.
	 */
	private $lastSitUsuariosUnidadesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SitUnidadesPeer';

	/**
	 * Get the [id_unidad] column value.
	 * 
	 * @return     int
	 */
	public function getIdUnidad()
	{
		return $this->id_unidad;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [correo] column value.
	 * 
	 * @return     string
	 */
	public function getCorreo()
	{
		return $this->correo;
	}

	/**
	 * Set the value of [id_unidad] column.
	 * 
	 * @param      int $v new value
	 * @return     SitUnidades The current object (for fluent API support)
	 */
	public function setIdUnidad($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_unidad !== $v) {
			$this->id_unidad = $v;
			$this->modifiedColumns[] = SitUnidadesPeer::ID_UNIDAD;
		}

		return $this;
	} // setIdUnidad()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     SitUnidades The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = SitUnidadesPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [correo] column.
	 * 
	 * @param      string $v new value
	 * @return     SitUnidades The current object (for fluent API support)
	 */
	public function setCorreo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->correo !== $v) {
			$this->correo = $v;
			$this->modifiedColumns[] = SitUnidadesPeer::CORREO;
		}

		return $this;
	} // setCorreo()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_unidad = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->descripcion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->correo = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 3; // 3 = SitUnidadesPeer::NUM_COLUMNS - SitUnidadesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating SitUnidades object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SitUnidadesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SitUnidadesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collBitCategoriasUnidadess = null;
			$this->lastBitCategoriasUnidadesCriteria = null;

			$this->collSitCategoriasUnidadess = null;
			$this->lastSitCategoriasUnidadesCriteria = null;

			$this->collSitTicketss = null;
			$this->lastSitTicketsCriteria = null;

			$this->collSitUsuariosUnidadess = null;
			$this->lastSitUsuariosUnidadesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SitUnidadesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSitUnidades:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SitUnidadesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSitUnidades:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SitUnidadesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSitUnidades:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSitUnidades:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SitUnidadesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SitUnidadesPeer::ID_UNIDAD;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SitUnidadesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdUnidad($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SitUnidadesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collBitCategoriasUnidadess !== null) {
				foreach ($this->collBitCategoriasUnidadess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSitCategoriasUnidadess !== null) {
				foreach ($this->collSitCategoriasUnidadess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSitTicketss !== null) {
				foreach ($this->collSitTicketss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSitUsuariosUnidadess !== null) {
				foreach ($this->collSitUsuariosUnidadess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = SitUnidadesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collBitCategoriasUnidadess !== null) {
					foreach ($this->collBitCategoriasUnidadess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSitCategoriasUnidadess !== null) {
					foreach ($this->collSitCategoriasUnidadess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSitTicketss !== null) {
					foreach ($this->collSitTicketss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSitUsuariosUnidadess !== null) {
					foreach ($this->collSitUsuariosUnidadess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SitUnidadesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdUnidad();
				break;
			case 1:
				return $this->getDescripcion();
				break;
			case 2:
				return $this->getCorreo();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SitUnidadesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdUnidad(),
			$keys[1] => $this->getDescripcion(),
			$keys[2] => $this->getCorreo(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SitUnidadesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdUnidad($value);
				break;
			case 1:
				$this->setDescripcion($value);
				break;
			case 2:
				$this->setCorreo($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SitUnidadesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdUnidad($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDescripcion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCorreo($arr[$keys[2]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);

		if ($this->isColumnModified(SitUnidadesPeer::ID_UNIDAD)) $criteria->add(SitUnidadesPeer::ID_UNIDAD, $this->id_unidad);
		if ($this->isColumnModified(SitUnidadesPeer::DESCRIPCION)) $criteria->add(SitUnidadesPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(SitUnidadesPeer::CORREO)) $criteria->add(SitUnidadesPeer::CORREO, $this->correo);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);

		$criteria->add(SitUnidadesPeer::ID_UNIDAD, $this->id_unidad);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdUnidad();
	}

	/**
	 * Generic method to set the primary key (id_unidad column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdUnidad($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of SitUnidades (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setCorreo($this->correo);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getBitCategoriasUnidadess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBitCategoriasUnidades($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSitCategoriasUnidadess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSitCategoriasUnidades($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSitTicketss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSitTickets($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSitUsuariosUnidadess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSitUsuariosUnidades($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdUnidad(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     SitUnidades Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SitUnidadesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SitUnidadesPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collBitCategoriasUnidadess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBitCategoriasUnidadess()
	 */
	public function clearBitCategoriasUnidadess()
	{
		$this->collBitCategoriasUnidadess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBitCategoriasUnidadess collection (array).
	 *
	 * By default this just sets the collBitCategoriasUnidadess collection to an empty array (like clearcollBitCategoriasUnidadess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBitCategoriasUnidadess()
	{
		$this->collBitCategoriasUnidadess = array();
	}

	/**
	 * Gets an array of BitCategoriasUnidades objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SitUnidades has previously been saved, it will retrieve
	 * related BitCategoriasUnidadess from storage. If this SitUnidades is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array BitCategoriasUnidades[]
	 * @throws     PropelException
	 */
	public function getBitCategoriasUnidadess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBitCategoriasUnidadess === null) {
			if ($this->isNew()) {
			   $this->collBitCategoriasUnidadess = array();
			} else {

				$criteria->add(BitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				BitCategoriasUnidadesPeer::addSelectColumns($criteria);
				$this->collBitCategoriasUnidadess = BitCategoriasUnidadesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				BitCategoriasUnidadesPeer::addSelectColumns($criteria);
				if (!isset($this->lastBitCategoriasUnidadesCriteria) || !$this->lastBitCategoriasUnidadesCriteria->equals($criteria)) {
					$this->collBitCategoriasUnidadess = BitCategoriasUnidadesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBitCategoriasUnidadesCriteria = $criteria;
		return $this->collBitCategoriasUnidadess;
	}

	/**
	 * Returns the number of related BitCategoriasUnidades objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related BitCategoriasUnidades objects.
	 * @throws     PropelException
	 */
	public function countBitCategoriasUnidadess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBitCategoriasUnidadess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				$count = BitCategoriasUnidadesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				if (!isset($this->lastBitCategoriasUnidadesCriteria) || !$this->lastBitCategoriasUnidadesCriteria->equals($criteria)) {
					$count = BitCategoriasUnidadesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collBitCategoriasUnidadess);
				}
			} else {
				$count = count($this->collBitCategoriasUnidadess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a BitCategoriasUnidades object to this object
	 * through the BitCategoriasUnidades foreign key attribute.
	 *
	 * @param      BitCategoriasUnidades $l BitCategoriasUnidades
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBitCategoriasUnidades(BitCategoriasUnidades $l)
	{
		if ($this->collBitCategoriasUnidadess === null) {
			$this->initBitCategoriasUnidadess();
		}
		if (!in_array($l, $this->collBitCategoriasUnidadess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBitCategoriasUnidadess, $l);
			$l->setSitUnidades($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SitUnidades is new, it will return
	 * an empty collection; or if this SitUnidades has previously
	 * been saved, it will retrieve related BitCategoriasUnidadess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SitUnidades.
	 */
	public function getBitCategoriasUnidadessJoinBitCategorias($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBitCategoriasUnidadess === null) {
			if ($this->isNew()) {
				$this->collBitCategoriasUnidadess = array();
			} else {

				$criteria->add(BitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				$this->collBitCategoriasUnidadess = BitCategoriasUnidadesPeer::doSelectJoinBitCategorias($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

			if (!isset($this->lastBitCategoriasUnidadesCriteria) || !$this->lastBitCategoriasUnidadesCriteria->equals($criteria)) {
				$this->collBitCategoriasUnidadess = BitCategoriasUnidadesPeer::doSelectJoinBitCategorias($criteria, $con, $join_behavior);
			}
		}
		$this->lastBitCategoriasUnidadesCriteria = $criteria;

		return $this->collBitCategoriasUnidadess;
	}

	/**
	 * Clears out the collSitCategoriasUnidadess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSitCategoriasUnidadess()
	 */
	public function clearSitCategoriasUnidadess()
	{
		$this->collSitCategoriasUnidadess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSitCategoriasUnidadess collection (array).
	 *
	 * By default this just sets the collSitCategoriasUnidadess collection to an empty array (like clearcollSitCategoriasUnidadess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSitCategoriasUnidadess()
	{
		$this->collSitCategoriasUnidadess = array();
	}

	/**
	 * Gets an array of SitCategoriasUnidades objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SitUnidades has previously been saved, it will retrieve
	 * related SitCategoriasUnidadess from storage. If this SitUnidades is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SitCategoriasUnidades[]
	 * @throws     PropelException
	 */
	public function getSitCategoriasUnidadess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitCategoriasUnidadess === null) {
			if ($this->isNew()) {
			   $this->collSitCategoriasUnidadess = array();
			} else {

				$criteria->add(SitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				SitCategoriasUnidadesPeer::addSelectColumns($criteria);
				$this->collSitCategoriasUnidadess = SitCategoriasUnidadesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				SitCategoriasUnidadesPeer::addSelectColumns($criteria);
				if (!isset($this->lastSitCategoriasUnidadesCriteria) || !$this->lastSitCategoriasUnidadesCriteria->equals($criteria)) {
					$this->collSitCategoriasUnidadess = SitCategoriasUnidadesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSitCategoriasUnidadesCriteria = $criteria;
		return $this->collSitCategoriasUnidadess;
	}

	/**
	 * Returns the number of related SitCategoriasUnidades objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SitCategoriasUnidades objects.
	 * @throws     PropelException
	 */
	public function countSitCategoriasUnidadess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSitCategoriasUnidadess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				$count = SitCategoriasUnidadesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				if (!isset($this->lastSitCategoriasUnidadesCriteria) || !$this->lastSitCategoriasUnidadesCriteria->equals($criteria)) {
					$count = SitCategoriasUnidadesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSitCategoriasUnidadess);
				}
			} else {
				$count = count($this->collSitCategoriasUnidadess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SitCategoriasUnidades object to this object
	 * through the SitCategoriasUnidades foreign key attribute.
	 *
	 * @param      SitCategoriasUnidades $l SitCategoriasUnidades
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSitCategoriasUnidades(SitCategoriasUnidades $l)
	{
		if ($this->collSitCategoriasUnidadess === null) {
			$this->initSitCategoriasUnidadess();
		}
		if (!in_array($l, $this->collSitCategoriasUnidadess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSitCategoriasUnidadess, $l);
			$l->setSitUnidades($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SitUnidades is new, it will return
	 * an empty collection; or if this SitUnidades has previously
	 * been saved, it will retrieve related SitCategoriasUnidadess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SitUnidades.
	 */
	public function getSitCategoriasUnidadessJoinSitCategorias($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitCategoriasUnidadess === null) {
			if ($this->isNew()) {
				$this->collSitCategoriasUnidadess = array();
			} else {

				$criteria->add(SitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				$this->collSitCategoriasUnidadess = SitCategoriasUnidadesPeer::doSelectJoinSitCategorias($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SitCategoriasUnidadesPeer::ID_UNIDAD, $this->id_unidad);

			if (!isset($this->lastSitCategoriasUnidadesCriteria) || !$this->lastSitCategoriasUnidadesCriteria->equals($criteria)) {
				$this->collSitCategoriasUnidadess = SitCategoriasUnidadesPeer::doSelectJoinSitCategorias($criteria, $con, $join_behavior);
			}
		}
		$this->lastSitCategoriasUnidadesCriteria = $criteria;

		return $this->collSitCategoriasUnidadess;
	}

	/**
	 * Clears out the collSitTicketss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSitTicketss()
	 */
	public function clearSitTicketss()
	{
		$this->collSitTicketss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSitTicketss collection (array).
	 *
	 * By default this just sets the collSitTicketss collection to an empty array (like clearcollSitTicketss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSitTicketss()
	{
		$this->collSitTicketss = array();
	}

	/**
	 * Gets an array of SitTickets objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SitUnidades has previously been saved, it will retrieve
	 * related SitTicketss from storage. If this SitUnidades is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SitTickets[]
	 * @throws     PropelException
	 */
	public function getSitTicketss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitTicketss === null) {
			if ($this->isNew()) {
			   $this->collSitTicketss = array();
			} else {

				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				SitTicketsPeer::addSelectColumns($criteria);
				$this->collSitTicketss = SitTicketsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				SitTicketsPeer::addSelectColumns($criteria);
				if (!isset($this->lastSitTicketsCriteria) || !$this->lastSitTicketsCriteria->equals($criteria)) {
					$this->collSitTicketss = SitTicketsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSitTicketsCriteria = $criteria;
		return $this->collSitTicketss;
	}

	/**
	 * Returns the number of related SitTickets objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SitTickets objects.
	 * @throws     PropelException
	 */
	public function countSitTicketss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSitTicketss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				$count = SitTicketsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				if (!isset($this->lastSitTicketsCriteria) || !$this->lastSitTicketsCriteria->equals($criteria)) {
					$count = SitTicketsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSitTicketss);
				}
			} else {
				$count = count($this->collSitTicketss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SitTickets object to this object
	 * through the SitTickets foreign key attribute.
	 *
	 * @param      SitTickets $l SitTickets
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSitTickets(SitTickets $l)
	{
		if ($this->collSitTicketss === null) {
			$this->initSitTicketss();
		}
		if (!in_array($l, $this->collSitTicketss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSitTicketss, $l);
			$l->setSitUnidades($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SitUnidades is new, it will return
	 * an empty collection; or if this SitUnidades has previously
	 * been saved, it will retrieve related SitTicketss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SitUnidades.
	 */
	public function getSitTicketssJoinSfGuardUserProfile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitTicketss === null) {
			if ($this->isNew()) {
				$this->collSitTicketss = array();
			} else {

				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				$this->collSitTicketss = SitTicketsPeer::doSelectJoinSfGuardUserProfile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

			if (!isset($this->lastSitTicketsCriteria) || !$this->lastSitTicketsCriteria->equals($criteria)) {
				$this->collSitTicketss = SitTicketsPeer::doSelectJoinSfGuardUserProfile($criteria, $con, $join_behavior);
			}
		}
		$this->lastSitTicketsCriteria = $criteria;

		return $this->collSitTicketss;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SitUnidades is new, it will return
	 * an empty collection; or if this SitUnidades has previously
	 * been saved, it will retrieve related SitTicketss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SitUnidades.
	 */
	public function getSitTicketssJoinSitCategorias($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitTicketss === null) {
			if ($this->isNew()) {
				$this->collSitTicketss = array();
			} else {

				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				$this->collSitTicketss = SitTicketsPeer::doSelectJoinSitCategorias($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

			if (!isset($this->lastSitTicketsCriteria) || !$this->lastSitTicketsCriteria->equals($criteria)) {
				$this->collSitTicketss = SitTicketsPeer::doSelectJoinSitCategorias($criteria, $con, $join_behavior);
			}
		}
		$this->lastSitTicketsCriteria = $criteria;

		return $this->collSitTicketss;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SitUnidades is new, it will return
	 * an empty collection; or if this SitUnidades has previously
	 * been saved, it will retrieve related SitTicketss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SitUnidades.
	 */
	public function getSitTicketssJoinSitSubcategorias($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitTicketss === null) {
			if ($this->isNew()) {
				$this->collSitTicketss = array();
			} else {

				$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

				$this->collSitTicketss = SitTicketsPeer::doSelectJoinSitSubcategorias($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SitTicketsPeer::ID_UNIDAD, $this->id_unidad);

			if (!isset($this->lastSitTicketsCriteria) || !$this->lastSitTicketsCriteria->equals($criteria)) {
				$this->collSitTicketss = SitTicketsPeer::doSelectJoinSitSubcategorias($criteria, $con, $join_behavior);
			}
		}
		$this->lastSitTicketsCriteria = $criteria;

		return $this->collSitTicketss;
	}

	/**
	 * Clears out the collSitUsuariosUnidadess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSitUsuariosUnidadess()
	 */
	public function clearSitUsuariosUnidadess()
	{
		$this->collSitUsuariosUnidadess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSitUsuariosUnidadess collection (array).
	 *
	 * By default this just sets the collSitUsuariosUnidadess collection to an empty array (like clearcollSitUsuariosUnidadess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSitUsuariosUnidadess()
	{
		$this->collSitUsuariosUnidadess = array();
	}

	/**
	 * Gets an array of SitUsuariosUnidades objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SitUnidades has previously been saved, it will retrieve
	 * related SitUsuariosUnidadess from storage. If this SitUnidades is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SitUsuariosUnidades[]
	 * @throws     PropelException
	 */
	public function getSitUsuariosUnidadess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitUsuariosUnidadess === null) {
			if ($this->isNew()) {
			   $this->collSitUsuariosUnidadess = array();
			} else {

				$criteria->add(SitUsuariosUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				SitUsuariosUnidadesPeer::addSelectColumns($criteria);
				$this->collSitUsuariosUnidadess = SitUsuariosUnidadesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SitUsuariosUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				SitUsuariosUnidadesPeer::addSelectColumns($criteria);
				if (!isset($this->lastSitUsuariosUnidadesCriteria) || !$this->lastSitUsuariosUnidadesCriteria->equals($criteria)) {
					$this->collSitUsuariosUnidadess = SitUsuariosUnidadesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSitUsuariosUnidadesCriteria = $criteria;
		return $this->collSitUsuariosUnidadess;
	}

	/**
	 * Returns the number of related SitUsuariosUnidades objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SitUsuariosUnidades objects.
	 * @throws     PropelException
	 */
	public function countSitUsuariosUnidadess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSitUsuariosUnidadess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SitUsuariosUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				$count = SitUsuariosUnidadesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SitUsuariosUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				if (!isset($this->lastSitUsuariosUnidadesCriteria) || !$this->lastSitUsuariosUnidadesCriteria->equals($criteria)) {
					$count = SitUsuariosUnidadesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSitUsuariosUnidadess);
				}
			} else {
				$count = count($this->collSitUsuariosUnidadess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SitUsuariosUnidades object to this object
	 * through the SitUsuariosUnidades foreign key attribute.
	 *
	 * @param      SitUsuariosUnidades $l SitUsuariosUnidades
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSitUsuariosUnidades(SitUsuariosUnidades $l)
	{
		if ($this->collSitUsuariosUnidadess === null) {
			$this->initSitUsuariosUnidadess();
		}
		if (!in_array($l, $this->collSitUsuariosUnidadess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSitUsuariosUnidadess, $l);
			$l->setSitUnidades($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SitUnidades is new, it will return
	 * an empty collection; or if this SitUnidades has previously
	 * been saved, it will retrieve related SitUsuariosUnidadess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SitUnidades.
	 */
	public function getSitUsuariosUnidadessJoinSfGuardUserProfile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SitUnidadesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSitUsuariosUnidadess === null) {
			if ($this->isNew()) {
				$this->collSitUsuariosUnidadess = array();
			} else {

				$criteria->add(SitUsuariosUnidadesPeer::ID_UNIDAD, $this->id_unidad);

				$this->collSitUsuariosUnidadess = SitUsuariosUnidadesPeer::doSelectJoinSfGuardUserProfile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SitUsuariosUnidadesPeer::ID_UNIDAD, $this->id_unidad);

			if (!isset($this->lastSitUsuariosUnidadesCriteria) || !$this->lastSitUsuariosUnidadesCriteria->equals($criteria)) {
				$this->collSitUsuariosUnidadess = SitUsuariosUnidadesPeer::doSelectJoinSfGuardUserProfile($criteria, $con, $join_behavior);
			}
		}
		$this->lastSitUsuariosUnidadesCriteria = $criteria;

		return $this->collSitUsuariosUnidadess;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collBitCategoriasUnidadess) {
				foreach ((array) $this->collBitCategoriasUnidadess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSitCategoriasUnidadess) {
				foreach ((array) $this->collSitCategoriasUnidadess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSitTicketss) {
				foreach ((array) $this->collSitTicketss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSitUsuariosUnidadess) {
				foreach ((array) $this->collSitUsuariosUnidadess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collBitCategoriasUnidadess = null;
		$this->collSitCategoriasUnidadess = null;
		$this->collSitTicketss = null;
		$this->collSitUsuariosUnidadess = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSitUnidades:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSitUnidades::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSitUnidades
