<?php

/**
 * Base class that represents a row from the 'lc_licencias' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 24 11:49:51 2012
 *
 * @package    lib.model.om
 */
abstract class BaseLcLicencias extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        LcLicenciasPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_licencia field.
	 * @var        int
	 */
	protected $id_licencia;

	/**
	 * The value for the id_responsable field.
	 * @var        int
	 */
	protected $id_responsable;

	/**
	 * The value for the nombre_licencia field.
	 * @var        string
	 */
	protected $nombre_licencia;

	/**
	 * The value for the numero field.
	 * @var        string
	 */
	protected $numero;

	/**
	 * The value for the fecha_compra field.
	 * @var        string
	 */
	protected $fecha_compra;

	/**
	 * The value for the fecha_vencimiento field.
	 * @var        string
	 */
	protected $fecha_vencimiento;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the bandera_correo field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $bandera_correo;

	/**
	 * The value for the tipo field.
	 * @var        string
	 */
	protected $tipo;

	/**
	 * @var        SfGuardUserProfile
	 */
	protected $aSfGuardUserProfile;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'LcLicenciasPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->bandera_correo = 0;
	}

	/**
	 * Initializes internal state of BaseLcLicencias object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id_licencia] column value.
	 * 
	 * @return     int
	 */
	public function getIdLicencia()
	{
		return $this->id_licencia;
	}

	/**
	 * Get the [id_responsable] column value.
	 * 
	 * @return     int
	 */
	public function getIdResponsable()
	{
		return $this->id_responsable;
	}

	/**
	 * Get the [nombre_licencia] column value.
	 * 
	 * @return     string
	 */
	public function getNombreLicencia()
	{
		return $this->nombre_licencia;
	}

	/**
	 * Get the [numero] column value.
	 * 
	 * @return     string
	 */
	public function getNumero()
	{
		return $this->numero;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_compra] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaCompra($format = 'Y-m-d')
	{
		if ($this->fecha_compra === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_compra);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_compra, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_vencimiento] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaVencimiento($format = 'Y-m-d')
	{
		if ($this->fecha_vencimiento === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_vencimiento);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_vencimiento, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [bandera_correo] column value.
	 * 
	 * @return     int
	 */
	public function getBanderaCorreo()
	{
		return $this->bandera_correo;
	}

	/**
	 * Get the [tipo] column value.
	 * 
	 * @return     string
	 */
	public function getTipo()
	{
		return $this->tipo;
	}

	/**
	 * Set the value of [id_licencia] column.
	 * 
	 * @param      int $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setIdLicencia($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_licencia !== $v) {
			$this->id_licencia = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::ID_LICENCIA;
		}

		return $this;
	} // setIdLicencia()

	/**
	 * Set the value of [id_responsable] column.
	 * 
	 * @param      int $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setIdResponsable($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_responsable !== $v) {
			$this->id_responsable = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::ID_RESPONSABLE;
		}

		if ($this->aSfGuardUserProfile !== null && $this->aSfGuardUserProfile->getUserId() !== $v) {
			$this->aSfGuardUserProfile = null;
		}

		return $this;
	} // setIdResponsable()

	/**
	 * Set the value of [nombre_licencia] column.
	 * 
	 * @param      string $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setNombreLicencia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre_licencia !== $v) {
			$this->nombre_licencia = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::NOMBRE_LICENCIA;
		}

		return $this;
	} // setNombreLicencia()

	/**
	 * Set the value of [numero] column.
	 * 
	 * @param      string $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setNumero($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->numero !== $v) {
			$this->numero = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::NUMERO;
		}

		return $this;
	} // setNumero()

	/**
	 * Sets the value of [fecha_compra] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setFechaCompra($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_compra !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_compra !== null && $tmpDt = new DateTime($this->fecha_compra)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_compra = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = LcLicenciasPeer::FECHA_COMPRA;
			}
		} // if either are not null

		return $this;
	} // setFechaCompra()

	/**
	 * Sets the value of [fecha_vencimiento] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setFechaVencimiento($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_vencimiento !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_vencimiento !== null && $tmpDt = new DateTime($this->fecha_vencimiento)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_vencimiento = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = LcLicenciasPeer::FECHA_VENCIMIENTO;
			}
		} // if either are not null

		return $this;
	} // setFechaVencimiento()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [bandera_correo] column.
	 * 
	 * @param      int $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setBanderaCorreo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bandera_correo !== $v || $this->isNew()) {
			$this->bandera_correo = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::BANDERA_CORREO;
		}

		return $this;
	} // setBanderaCorreo()

	/**
	 * Set the value of [tipo] column.
	 * 
	 * @param      string $v new value
	 * @return     LcLicencias The current object (for fluent API support)
	 */
	public function setTipo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tipo !== $v) {
			$this->tipo = $v;
			$this->modifiedColumns[] = LcLicenciasPeer::TIPO;
		}

		return $this;
	} // setTipo()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->bandera_correo !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_licencia = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_responsable = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->nombre_licencia = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->numero = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->fecha_compra = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fecha_vencimiento = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->descripcion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->bandera_correo = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->tipo = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = LcLicenciasPeer::NUM_COLUMNS - LcLicenciasPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating LcLicencias object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSfGuardUserProfile !== null && $this->id_responsable !== $this->aSfGuardUserProfile->getUserId()) {
			$this->aSfGuardUserProfile = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LcLicenciasPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = LcLicenciasPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSfGuardUserProfile = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LcLicenciasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseLcLicencias:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				LcLicenciasPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseLcLicencias:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LcLicenciasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseLcLicencias:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseLcLicencias:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				LcLicenciasPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSfGuardUserProfile !== null) {
				if ($this->aSfGuardUserProfile->isModified() || $this->aSfGuardUserProfile->isNew()) {
					$affectedRows += $this->aSfGuardUserProfile->save($con);
				}
				$this->setSfGuardUserProfile($this->aSfGuardUserProfile);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = LcLicenciasPeer::ID_LICENCIA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = LcLicenciasPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdLicencia($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += LcLicenciasPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSfGuardUserProfile !== null) {
				if (!$this->aSfGuardUserProfile->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSfGuardUserProfile->getValidationFailures());
				}
			}


			if (($retval = LcLicenciasPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = LcLicenciasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdLicencia();
				break;
			case 1:
				return $this->getIdResponsable();
				break;
			case 2:
				return $this->getNombreLicencia();
				break;
			case 3:
				return $this->getNumero();
				break;
			case 4:
				return $this->getFechaCompra();
				break;
			case 5:
				return $this->getFechaVencimiento();
				break;
			case 6:
				return $this->getDescripcion();
				break;
			case 7:
				return $this->getBanderaCorreo();
				break;
			case 8:
				return $this->getTipo();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = LcLicenciasPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdLicencia(),
			$keys[1] => $this->getIdResponsable(),
			$keys[2] => $this->getNombreLicencia(),
			$keys[3] => $this->getNumero(),
			$keys[4] => $this->getFechaCompra(),
			$keys[5] => $this->getFechaVencimiento(),
			$keys[6] => $this->getDescripcion(),
			$keys[7] => $this->getBanderaCorreo(),
			$keys[8] => $this->getTipo(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = LcLicenciasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdLicencia($value);
				break;
			case 1:
				$this->setIdResponsable($value);
				break;
			case 2:
				$this->setNombreLicencia($value);
				break;
			case 3:
				$this->setNumero($value);
				break;
			case 4:
				$this->setFechaCompra($value);
				break;
			case 5:
				$this->setFechaVencimiento($value);
				break;
			case 6:
				$this->setDescripcion($value);
				break;
			case 7:
				$this->setBanderaCorreo($value);
				break;
			case 8:
				$this->setTipo($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = LcLicenciasPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdLicencia($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdResponsable($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNombreLicencia($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNumero($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFechaCompra($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFechaVencimiento($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDescripcion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setBanderaCorreo($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTipo($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(LcLicenciasPeer::DATABASE_NAME);

		if ($this->isColumnModified(LcLicenciasPeer::ID_LICENCIA)) $criteria->add(LcLicenciasPeer::ID_LICENCIA, $this->id_licencia);
		if ($this->isColumnModified(LcLicenciasPeer::ID_RESPONSABLE)) $criteria->add(LcLicenciasPeer::ID_RESPONSABLE, $this->id_responsable);
		if ($this->isColumnModified(LcLicenciasPeer::NOMBRE_LICENCIA)) $criteria->add(LcLicenciasPeer::NOMBRE_LICENCIA, $this->nombre_licencia);
		if ($this->isColumnModified(LcLicenciasPeer::NUMERO)) $criteria->add(LcLicenciasPeer::NUMERO, $this->numero);
		if ($this->isColumnModified(LcLicenciasPeer::FECHA_COMPRA)) $criteria->add(LcLicenciasPeer::FECHA_COMPRA, $this->fecha_compra);
		if ($this->isColumnModified(LcLicenciasPeer::FECHA_VENCIMIENTO)) $criteria->add(LcLicenciasPeer::FECHA_VENCIMIENTO, $this->fecha_vencimiento);
		if ($this->isColumnModified(LcLicenciasPeer::DESCRIPCION)) $criteria->add(LcLicenciasPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(LcLicenciasPeer::BANDERA_CORREO)) $criteria->add(LcLicenciasPeer::BANDERA_CORREO, $this->bandera_correo);
		if ($this->isColumnModified(LcLicenciasPeer::TIPO)) $criteria->add(LcLicenciasPeer::TIPO, $this->tipo);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(LcLicenciasPeer::DATABASE_NAME);

		$criteria->add(LcLicenciasPeer::ID_LICENCIA, $this->id_licencia);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdLicencia();
	}

	/**
	 * Generic method to set the primary key (id_licencia column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdLicencia($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of LcLicencias (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdResponsable($this->id_responsable);

		$copyObj->setNombreLicencia($this->nombre_licencia);

		$copyObj->setNumero($this->numero);

		$copyObj->setFechaCompra($this->fecha_compra);

		$copyObj->setFechaVencimiento($this->fecha_vencimiento);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setBanderaCorreo($this->bandera_correo);

		$copyObj->setTipo($this->tipo);


		$copyObj->setNew(true);

		$copyObj->setIdLicencia(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     LcLicencias Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     LcLicenciasPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new LcLicenciasPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a SfGuardUserProfile object.
	 *
	 * @param      SfGuardUserProfile $v
	 * @return     LcLicencias The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSfGuardUserProfile(SfGuardUserProfile $v = null)
	{
		if ($v === null) {
			$this->setIdResponsable(NULL);
		} else {
			$this->setIdResponsable($v->getUserId());
		}

		$this->aSfGuardUserProfile = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SfGuardUserProfile object, it will not be re-added.
		if ($v !== null) {
			$v->addLcLicencias($this);
		}

		return $this;
	}


	/**
	 * Get the associated SfGuardUserProfile object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SfGuardUserProfile The associated SfGuardUserProfile object.
	 * @throws     PropelException
	 */
	public function getSfGuardUserProfile(PropelPDO $con = null)
	{
		if ($this->aSfGuardUserProfile === null && ($this->id_responsable !== null)) {
			$this->aSfGuardUserProfile = SfGuardUserProfilePeer::retrieveByPk($this->id_responsable);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSfGuardUserProfile->addLcLicenciass($this);
			 */
		}
		return $this->aSfGuardUserProfile;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aSfGuardUserProfile = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseLcLicencias:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseLcLicencias::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseLcLicencias
