<?php

/**
 * Base class that represents a row from the 'cp_controldepersonal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 31 11:39:54 2012
 *
 * @package    lib.model.om
 */
abstract class BaseCpControldepersonal extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CpControldepersonalPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_control field.
	 * @var        int
	 */
	protected $id_control;

	/**
	 * The value for the id_usuario field.
	 * @var        int
	 */
	protected $id_usuario;

	/**
	 * The value for the fecha_entrada field.
	 * @var        string
	 */
	protected $fecha_entrada;

	/**
	 * The value for the hora_entrada field.
	 * @var        string
	 */
	protected $hora_entrada;

	/**
	 * The value for the observacion_entrada field.
	 * @var        string
	 */
	protected $observacion_entrada;

	/**
	 * The value for the fecha_salida field.
	 * @var        string
	 */
	protected $fecha_salida;

	/**
	 * The value for the hora_salida field.
	 * @var        string
	 */
	protected $hora_salida;

	/**
	 * The value for the observacion_salida field.
	 * @var        string
	 */
	protected $observacion_salida;

	/**
	 * The value for the ip_entrada field.
	 * @var        string
	 */
	protected $ip_entrada;

	/**
	 * The value for the ip_salida field.
	 * @var        string
	 */
	protected $ip_salida;

	/**
	 * @var        SfGuardUserProfile
	 */
	protected $aSfGuardUserProfile;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'CpControldepersonalPeer';

	/**
	 * Get the [id_control] column value.
	 * 
	 * @return     int
	 */
	public function getIdControl()
	{
		return $this->id_control;
	}

	/**
	 * Get the [id_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getIdUsuario()
	{
		return $this->id_usuario;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_entrada] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaEntrada($format = 'Y-m-d')
	{
		if ($this->fecha_entrada === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_entrada);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_entrada, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [hora_entrada] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getHoraEntrada($format = 'H:i:s')
	{
		if ($this->hora_entrada === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->hora_entrada);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->hora_entrada, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [observacion_entrada] column value.
	 * 
	 * @return     string
	 */
	public function getObservacionEntrada()
	{
		return $this->observacion_entrada;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_salida] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaSalida($format = 'Y-m-d')
	{
		if ($this->fecha_salida === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_salida);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_salida, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [hora_salida] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getHoraSalida($format = 'H:i:s')
	{
		if ($this->hora_salida === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->hora_salida);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->hora_salida, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [observacion_salida] column value.
	 * 
	 * @return     string
	 */
	public function getObservacionSalida()
	{
		return $this->observacion_salida;
	}

	/**
	 * Get the [ip_entrada] column value.
	 * 
	 * @return     string
	 */
	public function getIpEntrada()
	{
		return $this->ip_entrada;
	}

	/**
	 * Get the [ip_salida] column value.
	 * 
	 * @return     string
	 */
	public function getIpSalida()
	{
		return $this->ip_salida;
	}

	/**
	 * Set the value of [id_control] column.
	 * 
	 * @param      int $v new value
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setIdControl($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_control !== $v) {
			$this->id_control = $v;
			$this->modifiedColumns[] = CpControldepersonalPeer::ID_CONTROL;
		}

		return $this;
	} // setIdControl()

	/**
	 * Set the value of [id_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setIdUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_usuario !== $v) {
			$this->id_usuario = $v;
			$this->modifiedColumns[] = CpControldepersonalPeer::ID_USUARIO;
		}

		if ($this->aSfGuardUserProfile !== null && $this->aSfGuardUserProfile->getUserId() !== $v) {
			$this->aSfGuardUserProfile = null;
		}

		return $this;
	} // setIdUsuario()

	/**
	 * Sets the value of [fecha_entrada] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setFechaEntrada($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_entrada !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_entrada !== null && $tmpDt = new DateTime($this->fecha_entrada)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_entrada = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = CpControldepersonalPeer::FECHA_ENTRADA;
			}
		} // if either are not null

		return $this;
	} // setFechaEntrada()

	/**
	 * Sets the value of [hora_entrada] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setHoraEntrada($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->hora_entrada !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->hora_entrada !== null && $tmpDt = new DateTime($this->hora_entrada)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->hora_entrada = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = CpControldepersonalPeer::HORA_ENTRADA;
			}
		} // if either are not null

		return $this;
	} // setHoraEntrada()

	/**
	 * Set the value of [observacion_entrada] column.
	 * 
	 * @param      string $v new value
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setObservacionEntrada($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->observacion_entrada !== $v) {
			$this->observacion_entrada = $v;
			$this->modifiedColumns[] = CpControldepersonalPeer::OBSERVACION_ENTRADA;
		}

		return $this;
	} // setObservacionEntrada()

	/**
	 * Sets the value of [fecha_salida] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setFechaSalida($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_salida !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_salida !== null && $tmpDt = new DateTime($this->fecha_salida)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_salida = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = CpControldepersonalPeer::FECHA_SALIDA;
			}
		} // if either are not null

		return $this;
	} // setFechaSalida()

	/**
	 * Sets the value of [hora_salida] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setHoraSalida($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->hora_salida !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->hora_salida !== null && $tmpDt = new DateTime($this->hora_salida)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->hora_salida = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = CpControldepersonalPeer::HORA_SALIDA;
			}
		} // if either are not null

		return $this;
	} // setHoraSalida()

	/**
	 * Set the value of [observacion_salida] column.
	 * 
	 * @param      string $v new value
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setObservacionSalida($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->observacion_salida !== $v) {
			$this->observacion_salida = $v;
			$this->modifiedColumns[] = CpControldepersonalPeer::OBSERVACION_SALIDA;
		}

		return $this;
	} // setObservacionSalida()

	/**
	 * Set the value of [ip_entrada] column.
	 * 
	 * @param      string $v new value
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setIpEntrada($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ip_entrada !== $v) {
			$this->ip_entrada = $v;
			$this->modifiedColumns[] = CpControldepersonalPeer::IP_ENTRADA;
		}

		return $this;
	} // setIpEntrada()

	/**
	 * Set the value of [ip_salida] column.
	 * 
	 * @param      string $v new value
	 * @return     CpControldepersonal The current object (for fluent API support)
	 */
	public function setIpSalida($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ip_salida !== $v) {
			$this->ip_salida = $v;
			$this->modifiedColumns[] = CpControldepersonalPeer::IP_SALIDA;
		}

		return $this;
	} // setIpSalida()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_control = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_usuario = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->fecha_entrada = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->hora_entrada = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->observacion_entrada = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fecha_salida = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->hora_salida = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->observacion_salida = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->ip_entrada = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->ip_salida = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = CpControldepersonalPeer::NUM_COLUMNS - CpControldepersonalPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating CpControldepersonal object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSfGuardUserProfile !== null && $this->id_usuario !== $this->aSfGuardUserProfile->getUserId()) {
			$this->aSfGuardUserProfile = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CpControldepersonalPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CpControldepersonalPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSfGuardUserProfile = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CpControldepersonalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCpControldepersonal:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				CpControldepersonalPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCpControldepersonal:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CpControldepersonalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCpControldepersonal:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCpControldepersonal:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				CpControldepersonalPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSfGuardUserProfile !== null) {
				if ($this->aSfGuardUserProfile->isModified() || $this->aSfGuardUserProfile->isNew()) {
					$affectedRows += $this->aSfGuardUserProfile->save($con);
				}
				$this->setSfGuardUserProfile($this->aSfGuardUserProfile);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CpControldepersonalPeer::ID_CONTROL;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CpControldepersonalPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdControl($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CpControldepersonalPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSfGuardUserProfile !== null) {
				if (!$this->aSfGuardUserProfile->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSfGuardUserProfile->getValidationFailures());
				}
			}


			if (($retval = CpControldepersonalPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CpControldepersonalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdControl();
				break;
			case 1:
				return $this->getIdUsuario();
				break;
			case 2:
				return $this->getFechaEntrada();
				break;
			case 3:
				return $this->getHoraEntrada();
				break;
			case 4:
				return $this->getObservacionEntrada();
				break;
			case 5:
				return $this->getFechaSalida();
				break;
			case 6:
				return $this->getHoraSalida();
				break;
			case 7:
				return $this->getObservacionSalida();
				break;
			case 8:
				return $this->getIpEntrada();
				break;
			case 9:
				return $this->getIpSalida();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CpControldepersonalPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdControl(),
			$keys[1] => $this->getIdUsuario(),
			$keys[2] => $this->getFechaEntrada(),
			$keys[3] => $this->getHoraEntrada(),
			$keys[4] => $this->getObservacionEntrada(),
			$keys[5] => $this->getFechaSalida(),
			$keys[6] => $this->getHoraSalida(),
			$keys[7] => $this->getObservacionSalida(),
			$keys[8] => $this->getIpEntrada(),
			$keys[9] => $this->getIpSalida(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CpControldepersonalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdControl($value);
				break;
			case 1:
				$this->setIdUsuario($value);
				break;
			case 2:
				$this->setFechaEntrada($value);
				break;
			case 3:
				$this->setHoraEntrada($value);
				break;
			case 4:
				$this->setObservacionEntrada($value);
				break;
			case 5:
				$this->setFechaSalida($value);
				break;
			case 6:
				$this->setHoraSalida($value);
				break;
			case 7:
				$this->setObservacionSalida($value);
				break;
			case 8:
				$this->setIpEntrada($value);
				break;
			case 9:
				$this->setIpSalida($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CpControldepersonalPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdControl($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdUsuario($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFechaEntrada($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setHoraEntrada($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setObservacionEntrada($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFechaSalida($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setHoraSalida($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setObservacionSalida($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIpEntrada($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIpSalida($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CpControldepersonalPeer::DATABASE_NAME);

		if ($this->isColumnModified(CpControldepersonalPeer::ID_CONTROL)) $criteria->add(CpControldepersonalPeer::ID_CONTROL, $this->id_control);
		if ($this->isColumnModified(CpControldepersonalPeer::ID_USUARIO)) $criteria->add(CpControldepersonalPeer::ID_USUARIO, $this->id_usuario);
		if ($this->isColumnModified(CpControldepersonalPeer::FECHA_ENTRADA)) $criteria->add(CpControldepersonalPeer::FECHA_ENTRADA, $this->fecha_entrada);
		if ($this->isColumnModified(CpControldepersonalPeer::HORA_ENTRADA)) $criteria->add(CpControldepersonalPeer::HORA_ENTRADA, $this->hora_entrada);
		if ($this->isColumnModified(CpControldepersonalPeer::OBSERVACION_ENTRADA)) $criteria->add(CpControldepersonalPeer::OBSERVACION_ENTRADA, $this->observacion_entrada);
		if ($this->isColumnModified(CpControldepersonalPeer::FECHA_SALIDA)) $criteria->add(CpControldepersonalPeer::FECHA_SALIDA, $this->fecha_salida);
		if ($this->isColumnModified(CpControldepersonalPeer::HORA_SALIDA)) $criteria->add(CpControldepersonalPeer::HORA_SALIDA, $this->hora_salida);
		if ($this->isColumnModified(CpControldepersonalPeer::OBSERVACION_SALIDA)) $criteria->add(CpControldepersonalPeer::OBSERVACION_SALIDA, $this->observacion_salida);
		if ($this->isColumnModified(CpControldepersonalPeer::IP_ENTRADA)) $criteria->add(CpControldepersonalPeer::IP_ENTRADA, $this->ip_entrada);
		if ($this->isColumnModified(CpControldepersonalPeer::IP_SALIDA)) $criteria->add(CpControldepersonalPeer::IP_SALIDA, $this->ip_salida);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CpControldepersonalPeer::DATABASE_NAME);

		$criteria->add(CpControldepersonalPeer::ID_CONTROL, $this->id_control);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdControl();
	}

	/**
	 * Generic method to set the primary key (id_control column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdControl($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of CpControldepersonal (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdUsuario($this->id_usuario);

		$copyObj->setFechaEntrada($this->fecha_entrada);

		$copyObj->setHoraEntrada($this->hora_entrada);

		$copyObj->setObservacionEntrada($this->observacion_entrada);

		$copyObj->setFechaSalida($this->fecha_salida);

		$copyObj->setHoraSalida($this->hora_salida);

		$copyObj->setObservacionSalida($this->observacion_salida);

		$copyObj->setIpEntrada($this->ip_entrada);

		$copyObj->setIpSalida($this->ip_salida);


		$copyObj->setNew(true);

		$copyObj->setIdControl(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     CpControldepersonal Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CpControldepersonalPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CpControldepersonalPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a SfGuardUserProfile object.
	 *
	 * @param      SfGuardUserProfile $v
	 * @return     CpControldepersonal The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSfGuardUserProfile(SfGuardUserProfile $v = null)
	{
		if ($v === null) {
			$this->setIdUsuario(NULL);
		} else {
			$this->setIdUsuario($v->getUserId());
		}

		$this->aSfGuardUserProfile = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SfGuardUserProfile object, it will not be re-added.
		if ($v !== null) {
			$v->addCpControldepersonal($this);
		}

		return $this;
	}


	/**
	 * Get the associated SfGuardUserProfile object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SfGuardUserProfile The associated SfGuardUserProfile object.
	 * @throws     PropelException
	 */
	public function getSfGuardUserProfile(PropelPDO $con = null)
	{
		if ($this->aSfGuardUserProfile === null && ($this->id_usuario !== null)) {
			$this->aSfGuardUserProfile = SfGuardUserProfilePeer::retrieveByPk($this->id_usuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSfGuardUserProfile->addCpControldepersonals($this);
			 */
		}
		return $this->aSfGuardUserProfile;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aSfGuardUserProfile = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseCpControldepersonal:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseCpControldepersonal::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseCpControldepersonal
