generator:
  class: sfPropelGenerator
  param:
    model_class:           SitUnidades
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              SitUnidades
    plural:                SitUnidadess
    route_prefix:          sit_unidades
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
