<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/19 13:18:24

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:dbname=Telesur;host=localhost',
  'username' => 'postgres',
  'password' => 'postgres',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
