generator:
  class: sfPropelGenerator
  param:
    model_class:           MmEquiposTransmision
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              MmEquiposTransmision
    plural:                MmEquiposTransmisions
    route_prefix:          mm_equipos_transmision
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
