generator:
  class: sfPropelGenerator
  param:
    model_class:           TraDatosExternos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              TraDatosExternos
    plural:                TraDatosExternoss
    route_prefix:          tra_datos_externos
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        object_actions: {}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
