<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/21 09:21:22

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:dbname=Telesur;host=localhost',
  'username' => 'postgres',
  'password' => '..*t3l35ur*..',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
