<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/09/19 11:56:43
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'menu_administracion',
      1 => 'admin_usuarios',
    ),
  ),
);
