<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/02/13 10:37:41
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'menu_administracion',
      1 => 'admin_grupos',
    ),
  ),
);
