<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/11/11 09:42:33
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'menu_administracion',
      1 => 'admin_permisos',
    ),
  ),
);
