<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/09/21 09:21:22
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => 'on',
  ),
);
