<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/11 14:34:05
sfConfig::add(array(
  'mod_administracion_enabled' => true,
  'mod_administracion_view_class' => 'sfPHP',
));
