<?php


/**
 * Skeleton subclass for performing query and update operations on the 'bit_bitacora' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Oct 22 15:27:18 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BitBitacoraPeer extends BaseBitBitacoraPeer {

    static public function guardar($idu, $datos){
        
        $a=new BitBitacora;
        $a->setIdUsuario($idu);
        $a->setIdSubcategoria($datos['id_subcategoria']);
        $a->setDescripcion($datos['observaciones']);
        $a->setFecha($datos['fecha']);
        $a->setHora($datos['hora']['hour'].":".$datos['hora']['minute']);
        if($a->save()) return "Datos Guardados";
        else return false;
        
    }
    
} // BitBitacoraPeer
