<?php


/**
 * Skeleton subclass for performing query and update operations on the 'ct_constancias' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Apr 18 16:14:52 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CtConstanciasPeer extends BaseCtConstanciasPeer {

    	public static function guarda_constancia($datos,$idu){

		$tk=new CtConstancias();
		$tk->setIdSolicitante($idu);
		$tk->setFechaSolicitud(date("d-m-Y"));
		$tk->setTipoConstancia(trim($datos['tipo']));
		
		if(isset($datos['bono']))
		$tk->setBonoAlimentacion(true);
                
                else 
		$tk->setBonoAlimentacion(false);
                
		$tk->setMotivo(strtolower($datos['motivo']));
		$tk->setDirigidoA(strtolower($datos['dirigida']));
		$tk->setEstatus('n');
		if($tk->save())return "Datos guardados exitosamente";
		else return false;


	}
} // CtConstanciasPeer
