<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cv_visitas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct 30 16:21:54 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CvVisitasPeer extends BaseCvVisitasPeer {
     public static function guarda_visita($datos,$idusuario){
  
            $a = new CvVisitas;        
            $a->setIdUsuario($idusuario);
            $a->setFechaEntrada(date("d-m-Y"));
            $a->setHoraEntrada(date("G:i:s"));
            $a->setContacto($datos['contacto']);
            $a->setObservaciones($datos['observaciones']);
            $a->setNumCarnet($datos['num_carnet']);           
            $a->save();

    }
} // CvVisitasPeer
