<?php


/**
 * Skeleton subclass for performing query and update operations on the 'est_productos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug  6 13:54:26 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EstProductosPeer extends BaseEstProductosPeer {

} // EstProductosPeer
