<?php


/**
 * Skeleton subclass for performing query and update operations on the 'mm_ubicaciones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep 14 15:17:22 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MmUbicacionesPeer extends BaseMmUbicacionesPeer {
    
    public static function guarda_ubicacion($datos){
        
        $a=new MmUbicaciones;
        $a->setIdPais($datos['id_pais']);
        $a->setIdProducto($datos['id_producto']);
        $a->setDescripcion($datos['descripcion']);
        $a->setCantidad($datos['cantidad']);
        $a->setTipoProducto('et');

        if($a->save())return "Ubicación guardad exitosamente."; else return "Operación inválida.S";
        
        
    }
} // MmUbicacionesPeer
