<?php


/**
 * Skeleton subclass for representing a row from the 'sit_categorias' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Apr 18 16:14:53 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SitCategorias extends BaseSitCategorias {
    
    public function __toString(){
        
        return $this->getDescripcion();
        
    }

} // SitCategorias
