<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/12/03 10:43:36
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'estudios_admin',
    ),
  ),
);
