<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/17 11:01:19
sfConfig::add(array(
  'mod_equiposdetransmision_enabled' => true,
  'mod_equiposdetransmision_view_class' => 'sfPHP',
));
