<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/02/06 11:32:24
sfConfig::add(array(
  'mod_equiposdetransmision_enabled' => true,
  'mod_equiposdetransmision_view_class' => 'sfPHP',
));
