<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/23 11:54:22
sfConfig::add(array(
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_sf_guard_plugin_check_password_callable' => array (
  0 => 'ldap',
  1 => 'checkPassword',
),
));
