# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sit
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [general.css,menu.css,crud.css,tcal.css,sit.css,gips.css]

  javascripts:    [jquery.js,menu.js,funciones.js,tcal.js,ajax.js,ajax_refresh.js,gips.js]

  has_layout:     true
  layout:         layout
