<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/19 13:13:45
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 
    array (
      0 => 'app_creatv',
    ),
  ),
);
